const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n||0);
function go(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=(e)=>{e.preventDefault();go(b.dataset.go)});

let step=1, hasChildren=true, childSeq=0;
function showStep(n){step=n;document.querySelectorAll('.wizard-step').forEach(s=>s.classList.toggle('active-step',+s.dataset.step===n));$('progressFill').style.width=(n/3*100)+'%';$('progressText').textContent=`Step ${n} of 3`}
document.querySelectorAll('.nextStep').forEach(b=>b.onclick=()=>showStep(Math.min(3,step+1)));
document.querySelectorAll('.prevStep').forEach(b=>b.onclick=()=>showStep(Math.max(1,step-1)));
function syncHousing(){
 const renting=$('housing').value==='rent';
 $('rentWrap').style.display=renting?'flex':'none';
 if(!renting) $('rent').value=0;
}
$('housing').onchange=syncHousing;
function syncRelationship(){
 const coupled=$('relationship').value==='couple';
 $('partnerFields').style.display=coupled?'grid':'none';
 $('partner').closest('label').style.display=coupled?'flex':'none';
 refreshIncome();
}
$('relationship').onchange=syncRelationship;
document.querySelectorAll('[data-children]').forEach(b=>b.onclick=()=>{hasChildren=b.dataset.children==='yes';document.querySelectorAll('[data-children]').forEach(x=>x.classList.toggle('selected',x===b));$('childrenArea').style.display=hasChildren?'block':'none';if(hasChildren&&!document.querySelector('.child-card')) addChild()});
function addChild(){
 childSeq++; const d=document.createElement('div');d.className='child-card';d.innerHTML=`<div class="child-top"><h4>Child ${childSeq}</h4><button type="button" class="remove-child">Remove</button></div><div class="child-grid">
 <label>Date of birth<input class="childDob" type="date" value="2022-01-01"></label>
 <label>In approved childcare?<select class="childCare"><option value="no">No</option><option value="yes">Yes</option></select></label>
 <label>In secondary school?<select class="secondary"><option value="no">No</option><option value="yes">Yes</option></select></label></div>`;
 d.querySelector('.remove-child').onclick=()=>d.remove();$('childrenList').appendChild(d)
}
$('addChild').onclick=addChild; addChild();

function age(d){if(!d)return null;let b=new Date(d+'T00:00:00'),t=new Date(),a=t.getFullYear()-b.getFullYear();if(t<new Date(t.getFullYear(),b.getMonth(),b.getDate()))a--;return a}
function kids(){return [...document.querySelectorAll('.child-card')].map(c=>({age:age(c.querySelector('.childDob').value),childcare:c.querySelector('.childCare').value==='yes',secondary:c.querySelector('.secondary').value==='yes'}))}
function baseIncome(){const o=parseFloat($('annualOverride').value);const own=Number.isFinite(o)&&o>0?o:(+$('rate').value||0)*(+$('hours').value||0)*52+(+$('extras').value||0);return own+($('relationship').value==='couple'?(+$('partner').value||0):0)+(+$('otherIncome').value||0)}
function refreshIncome(){const t=baseIncome();$('householdTotal').textContent=money(t);$('incomeSlider').value=Math.min(600000,Math.round(t/1000)*1000);$('sliderValue').textContent=money(+$('incomeSlider').value)}
['rate','hours','extras','annualOverride','partner','otherIncome'].forEach(id=>$(id).addEventListener('input',refreshIncome));$('incomeSlider').oninput=()=>$('sliderValue').textContent=money(+$('incomeSlider').value);

function ccsRate(i){if(i<=88520)return 90;if(i>=538520)return 0;return Math.max(0,90-Math.floor((i-88520)/5000))}
function card(type,name,estimate,why,url){return `<article class="result ${type}"><span class="tag">${type==='calculated'?'CALCULATED ESTIMATE':'MAY BE WORTH CHECKING'}</span><h3>${name}</h3><div class="estimate">${estimate}</div><p>${why}</p>${url?`<a class="source-link" target="_blank" rel="noopener" href="${url}">Official government information →</a>`:''}</article>`}
$('calculateBtn').onclick=()=>{
 const income=+$('incomeSlider').value,K=hasChildren?kids():[],rel=$('relationship').value,housing=$('housing').value,sit=$('situation').value;
 let r=[],eligibleKids=K.filter(k=>k.age!==null && (k.age<=15 || (k.age<=19&&k.secondary))),cc=K.filter(k=>k.childcare&&k.age!==null&&k.age<=13&&!k.secondary);
 if(eligibleKids.length){
  let max=eligibleKids.reduce((s,k)=>s+(k.age<=12?235.48:306.46),0);
  if(income<=69131){
    r.push(card('calculated','Family Tax Benefit Part A',`Up to ${money(max)}/fortnight`,'Your modelled income is within the current maximum-rate income-test band. This is still a guide: care percentage, maintenance income and other eligibility rules can change the actual amount.','https://www.servicesaustralia.gov.au/family-tax-benefit-part-payment-rates?context=22151'));
  } else {
    let desc=income<=123078?'Your income is in the current 20c-per-$1 taper range. The exact amount depends on child ages, base-rate floors, care percentage, maintenance income and other FTB rules.':'Your income is above the second current FTB Part A threshold. A further income test may apply, and the exact result depends on your children and other FTB rules.';
    r.push(card('discovery','Family Tax Benefit Part A','Income-tested — calculate next',desc,'https://www.servicesaustralia.gov.au/income-test-for-family-tax-benefit-part?context=22151'));
  }
 }
 if(cc.length){let pct=ccsRate(income);r.push(card('calculated','Child Care Subsidy',`${pct}% standard CCS rate`,`Income-based standard CCS percentage estimate. Actual subsidy also depends on approved care, hourly fee/cap, subsidised hours and other rules. Higher CCS can apply to some families with more than one eligible child aged 5 or younger.`,'https://www.servicesaustralia.gov.au/your-income-can-affect-child-care-subsidy?context=41186'))}
 if(housing==='rent')r.push(card('discovery','Rent Assistance','Check eligibility','Rent Assistance may be added to certain qualifying payments. Your underlying payment, rent and family circumstances determine eligibility and rate.','https://www.servicesaustralia.gov.au/rent-assistance'));
 if(K.length && ((rel==='single'&&Math.min(...K.map(k=>k.age))<14)||(rel==='couple'&&Math.min(...K.map(k=>k.age))<6)))r.push(card('discovery','Parenting Payment','Check eligibility','Your family profile triggers a Parenting Payment check. Individual fortnightly income, partner income and assets are needed for the full rate calculation.','https://www.servicesaustralia.gov.au/parenting-payment'));
 if(sit==='jobseeker')r.push(card('discovery','JobSeeker Payment','Check eligibility','Your work situation triggers a JobSeeker check. Income, assets and other eligibility conditions apply.','https://www.servicesaustralia.gov.au/jobseeker-payment'));
 if(sit==='student')r.push(card('discovery','Student & apprentice support','Check multiple programs','Youth Allowance, Austudy, ABSTUDY and related study support may be relevant depending on age, course, independence and living arrangements.','https://www.servicesaustralia.gov.au/students-and-trainees'));
 if(sit==='carer'||$('careSomeone').value==='yes')r.push(card('discovery','Carer support','Check multiple programs','Carer Payment, Carer Allowance and related supplements may be relevant. Care requirements and means tests vary.','https://www.servicesaustralia.gov.au/caring-for-someone'));
 if(sit==='disability'||$('workDisability').value==='yes')r.push(card('discovery','Disability support','Check multiple programs','Disability Support Pension, Mobility Allowance and other support may be relevant. Medical and non-medical eligibility requires an official assessment.','https://www.servicesaustralia.gov.au/living-with-disability'));
 if(age($('yourDob').value)>=67||sit==='retired')r.push(card('discovery','Age Pension & seniors support','Check eligibility','Age, residence, income and assets rules apply. Concession cards may also be relevant.','https://www.servicesaustralia.gov.au/age-pension'));
 if(!r.length)r.push(card('discovery','Government support search','No obvious major payment yet','Your profile does not currently trigger one of the major common-payment categories. State, territory and concession programs can still be relevant.'));
 let x=[];
 // Separate discovery catalogue: these are surfaced without pretending a full eligibility assessment has been completed.
 if(K.length){
   x.push(card('discovery','Family Tax Benefit Part B','Worth checking','FTB Part B supports some single-parent, grandparent-carer and one-main-income families. Age of the youngest child and the secondary earner’s income are important.','https://www.servicesaustralia.gov.au/family-tax-benefit-part-b'));
   x.push(card('discovery','Health & concession cards','Worth checking','Depending on household income and the payments you receive, a Health Care Card, Low Income Health Care Card or other concession card may be relevant.','https://www.servicesaustralia.gov.au/concession-and-health-care-cards'));
 }
 if(K.some(k=>k.age!==null && k.age<1)){
   x.push(card('discovery','New baby support','Worth checking','A recent birth can trigger checks for Parental Leave Pay and, in some circumstances, Newborn Upfront Payment and Newborn Supplement. These payments interact with other family assistance.','https://www.servicesaustralia.gov.au/having-baby'));
 }
 if(cc.length){
   x.push(card('discovery','Additional Child Care Subsidy','Worth checking','Some families can receive extra childcare assistance in specific circumstances, including transition to work, temporary financial hardship, grandparent care or child wellbeing situations.','https://www.servicesaustralia.gov.au/additional-child-care-subsidy'));
 }
 if($('careSomeone').value==='yes'||sit==='carer'){
   x.push(card('discovery','Carer Allowance & supplements','Worth checking','Carer Allowance can have different eligibility rules from Carer Payment, so it is worth checking separately along with related supplements.','https://www.servicesaustralia.gov.au/carer-allowance'));
 }
 if($('workDisability').value==='yes'||sit==='disability'){
   x.push(card('discovery','Mobility & disability-related assistance','Worth checking','Depending on work, study and disability circumstances, support beyond DSP may be relevant.','https://www.servicesaustralia.gov.au/living-with-disability'));
 }
 if(sit==='student'){
   x.push(card('discovery','Education supplements & help','Worth checking','Study support can include more than a base payment. Depending on circumstances, supplements, loans and relocation-related assistance may also be relevant.','https://www.servicesaustralia.gov.au/students-and-trainees'));
 }
 if(housing==='rent'){
   x.push(card('discovery','State housing & cost-of-living help','Check your state','Your state or territory may offer concessions or housing-related assistance in addition to Commonwealth payments. V4 flags this for the state-program catalogue.','https://www.servicesaustralia.gov.au/concessions'));
 }
 x.push(card('discovery','State & territory concessions','Run local check',`Your profile is in ${$('personState').value}. Electricity, transport, rates, education and other concessions can be administered outside Centrelink, so these should be checked separately.`,null));
 $('extraResults').innerHTML=x.join('');
 $('extraSection').style.display=x.length?'block':'none';
 $('results').innerHTML=r.join('');$('matchSummary').textContent=`Based on a modelled household income of ${money(income)} and ${K.length} child${K.length===1?'':'ren'} in your profile.`;
 $('incomeInsight').innerHTML=`<b>Why this is useful:</b> calculated estimates are shown separately from programs that need more information or an official assessment. Rules basis: September 2026.`;
 go('matches')
};

$('grantBtn').onclick=()=>{const state=$('state').value,industry=$('industry').value||'your industry',funding=$('funding').value,emp=+$('employees').value,turn=+$('turnover').value;$('grantResults').innerHTML=card('discovery',`${funding} grants & programs`,'Live programs change',`Profile match: ${state}, ${industry}, ${emp} employees, ${money(turn)} turnover. Current grant rounds should be verified against official government sources.`,'https://business.gov.au/grants-and-programs')+card('discovery','Business advice & support','Also worth checking','Government-funded business advisers, training and support can be useful even where a cash grant is not available.','https://business.gov.au/expertise-and-advice')};

const SUPPORT_CATALOGUE = [
 {n:"Family Tax Benefit",c:"Families",k:"family children kids child ftb tax benefit raising kids",s:"Help with the cost of raising children.",who:"Families caring for dependent children. Income, child age, care percentage and other family circumstances affect eligibility and rate.",amount:"Rates vary by child age, family income and circumstances.",need:"Family income estimate, child details and care arrangements.",apply:"Usually claimed through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/family-tax-benefit"},
 {n:"Child Care Subsidy",c:"Families",k:"childcare day care child care ccs daycare",s:"Helps eligible families with the cost of approved child care.",who:"Families using approved child care who meet eligibility requirements.",amount:"The subsidy percentage depends mainly on family income, with other rules affecting subsidised hours and the amount paid.",need:"Family income, child details and approved child-care information.",apply:"Claim through Centrelink/myGov and confirm enrolment details.",u:"https://www.servicesaustralia.gov.au/child-care-subsidy"},
 {n:"Additional Child Care Subsidy",c:"Families",k:"extra childcare hardship grandparent transition work child wellbeing accs",s:"Extra child-care assistance for certain circumstances.",who:"May apply for child wellbeing, grandparent carers, temporary financial hardship or transition to work.",amount:"Higher assistance can apply depending on the ACCS category.",need:"Child-care details and evidence relevant to the applicable category.",apply:"Claim or assessment pathway depends on the ACCS category.",u:"https://www.servicesaustralia.gov.au/additional-child-care-subsidy"},
 {n:"Parenting Payment",c:"Families",k:"parent parenting young child mum dad single parent",s:"Income support for the main carer of a young child.",who:"Main carers who meet child-age, income, assets and other eligibility rules.",amount:"Fortnightly rates depend on whether you are single or partnered and your income.",need:"Income, assets, partner and child details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/parenting-payment"},
 {n:"Parental Leave Pay",c:"Families",k:"baby newborn birth parental leave maternity paternity ppl",s:"Government-funded parental leave pay for eligible parents.",who:"Parents who meet work, income and other eligibility rules for a birth or adoption.",amount:"Paid for an eligible period at the applicable government rate.",need:"Work history, income, child/birth or adoption details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/parental-leave-pay"},
 {n:"Newborn Upfront Payment and Newborn Supplement",c:"Families",k:"new baby newborn birth payment supplement",s:"Support for some families after a new baby joins the family.",who:"May apply where the family is eligible for FTB Part A and is not receiving Parental Leave Pay for that child.",amount:"Depends on family circumstances and eligibility.",need:"Newborn and family income details.",apply:"Usually assessed with Family Tax Benefit.",u:"https://www.servicesaustralia.gov.au/newborn-upfront-payment-and-newborn-supplement"},
 {n:"Stillborn Baby Payment",c:"Families",k:"stillborn stillbirth baby bereavement",s:"A payment for eligible families following a stillbirth.",who:"Eligibility depends on the circumstances and applicable income rules.",amount:"A lump-sum payment may apply.",need:"Relevant birth and family details.",apply:"Services Australia provides the claim pathway.",u:"https://www.servicesaustralia.gov.au/stillborn-baby-payment"},
 {n:"Double Orphan Pension",c:"Families",k:"orphan child care double orphan",s:"Help with the costs of caring for an eligible orphaned child.",who:"People caring for a child whose circumstances meet the Double Orphan Pension rules.",amount:"A fortnightly payment may apply.",need:"Child and caring-arrangement details.",apply:"Check the Services Australia claim process.",u:"https://www.servicesaustralia.gov.au/double-orphan-pension"},
 {n:"JobSeeker Payment",c:"Work",k:"job lost job unemployed unemployment looking work sick injured short term",s:"Income support while looking for work or when temporarily unable to do usual work or study.",who:"Generally people from age 22 to Age Pension age who meet income, assets and other rules.",amount:"Fortnightly rate depends on age, partner status, children and income.",need:"Income, assets, partner and work circumstances.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/jobseeker-payment"},
 {n:"Youth Allowance",c:"Study",k:"youth allowance young student apprentice job seeker study uni tafe",s:"Support for eligible young students, apprentices and job seekers.",who:"May apply to students/apprentices aged 24 or younger and job seekers aged 21 or younger, subject to rules.",amount:"Rates depend on age, living arrangements, independence and income tests.",need:"Study/work, living, parental/partner income and independence details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/youth-allowance"},
 {n:"Austudy",c:"Study",k:"austudy study mature student apprentice uni tafe 25",s:"Income support for eligible students and Australian Apprentices aged 25 or older.",who:"Full-time students or Australian Apprentices who meet age, study, income and assets rules.",amount:"Fortnightly rate varies with circumstances.",need:"Course/apprenticeship, income, assets and partner details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/austudy"},
 {n:"ABSTUDY",c:"Study",k:"abstudy aboriginal torres strait islander study apprentice education",s:"A group of payments and support for eligible Aboriginal and Torres Strait Islander students and apprentices.",who:"Eligibility varies by study, apprenticeship and personal circumstances.",amount:"Different ABSTUDY components have different rates and purposes.",need:"Study and personal circumstances.",apply:"Check the relevant ABSTUDY claim pathway.",u:"https://www.servicesaustralia.gov.au/abstudy"},
 {n:"Tertiary Access Payment",c:"Study",k:"tertiary access regional remote move university uni study relocation",s:"A one-off payment for eligible regional or remote students moving for tertiary study.",who:"Certain students moving from regional or remote areas for tertiary education.",amount:"One-off support; amount depends on eligibility rules.",need:"Home location, study and relocation details.",apply:"Claim through the applicable Services Australia process.",u:"https://www.servicesaustralia.gov.au/tertiary-access-payment"},
 {n:"Pensioner Education Supplement",c:"Study",k:"pension education supplement study pes",s:"Helps some payment recipients with study costs.",who:"People receiving certain eligible payments who undertake approved study.",amount:"A supplementary payment may apply.",need:"Current payment and course details.",apply:"Check eligibility and claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/pensioner-education-supplement"},
 {n:"Student Start-up Loan",c:"Study",k:"student startup loan study uni loan",s:"A voluntary loan for eligible higher-education students receiving certain study payments.",who:"Eligible students receiving qualifying study payments.",amount:"Loan amounts and repayment rules apply.",need:"Study and payment details.",apply:"Apply through Services Australia if eligible.",u:"https://www.servicesaustralia.gov.au/student-start-up-loan"},
 {n:"Carer Payment",c:"Carers",k:"carer caring disability illness frail aged full time care",s:"Income support if you provide constant care to someone with disability, illness or who is frail aged.",who:"Carers meeting care, income, assets and other eligibility rules.",amount:"Fortnightly pension rates depend on relationship and means testing.",need:"Care needs, medical information, income and assets.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/carer-payment"},
 {n:"Carer Allowance",c:"Carers",k:"carer allowance caring child adult disability illness",s:"A supplementary payment for eligible people providing daily care.",who:"Carers whose care recipient meets the applicable disability/medical and care requirements.",amount:"A supplementary payment; different means-testing rules apply from Carer Payment.",need:"Care and medical information plus income details where required.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/carer-allowance"},
 {n:"Carer Supplement",c:"Carers",k:"carer supplement annual caring",s:"An annual supplement for eligible recipients of certain carer payments.",who:"Generally paid automatically to eligible recipients at the qualifying time.",amount:"Annual supplement amount depends on qualifying payments.",need:"Usually no separate claim if already eligible.",apply:"Generally automatic where eligibility is met.",u:"https://www.servicesaustralia.gov.au/carer-supplement"},
 {n:"Carer Adjustment Payment",c:"Carers",k:"carer adjustment child catastrophic event disability care",s:"A one-off payment for some families caring for a child after a catastrophic event.",who:"Families meeting specific care and financial-impact criteria.",amount:"A one-off payment may be available.",need:"Evidence of the event, care needs and family circumstances.",apply:"Special claim process applies.",u:"https://www.servicesaustralia.gov.au/carer-adjustment-payment"},
 {n:"Disability Support Pension",c:"Disability",k:"dsp disability pension permanent condition unable work health",s:"Income support for eligible people with a long-term condition that significantly limits work.",who:"Medical and non-medical eligibility rules apply, including impairment and work-capacity requirements.",amount:"Pension rate depends on age, relationship, income and assets.",need:"Medical evidence, work capacity, income and assets.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/disability-support-pension"},
 {n:"Mobility Allowance",c:"Disability",k:"mobility disability transport travel work study public transport",s:"Help with travel costs for some people with disability, illness or injury who cannot use public transport without substantial assistance.",who:"Work, study or job-search participation and disability-related rules apply.",amount:"A fortnightly allowance may apply.",need:"Disability, transport and participation details.",apply:"Claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/mobility-allowance"},
 {n:"Essential Medical Equipment Payment",c:"Disability",k:"medical equipment electricity power heating cooling equipment health",s:"An annual payment to help with additional energy costs from eligible medical equipment or medically required heating/cooling.",who:"Concession-card and medical-equipment/condition requirements apply.",amount:"Annual assistance is available for eligible equipment or heating/cooling.",need:"Concession details and medical/equipment evidence.",apply:"Claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/essential-medical-equipment-payment"},
 {n:"Age Pension",c:"Older Australians",k:"age pension retirement older senior 67",s:"Income support for eligible older Australians.",who:"People who have reached Age Pension age and meet residence, income and assets rules.",amount:"Pension rate depends on relationship, income and assets.",need:"Income, assets, partner and residence information.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/age-pension"},
 {n:"Commonwealth Seniors Health Card",c:"Concessions",k:"senior health card retirees older concession cshc",s:"A concession card for eligible people of Age Pension age who meet the income test but may not receive a pension.",who:"Age Pension age, residence and income rules apply.",amount:"Not a cash payment; provides access to concessions and cheaper medicines/health services in relevant circumstances.",need:"Income, age and residence details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/commonwealth-seniors-health-card"},
 {n:"Low Income Health Care Card",c:"Concessions",k:"low income health care card concession cheap medicine medical",s:"A concession card for eligible people on a low income.",who:"Residence, age/independence and income-test rules apply.",amount:"Not a cash payment; can provide access to concessions.",need:"Recent income and residence details.",apply:"Claim through Centrelink/myGov.",u:"https://www.servicesaustralia.gov.au/low-income-health-care-card"},
 {n:"Pensioner Concession Card",c:"Concessions",k:"pensioner concession card cheap medicine transport rates",s:"A concession card generally linked to qualifying pension or payment status.",who:"Issued to recipients of certain pensions/payments and some other eligible groups.",amount:"Not a cash payment; concessions vary by service and state/territory.",need:"Usually linked to qualifying payment status.",apply:"Often issued automatically when eligible.",u:"https://www.servicesaustralia.gov.au/pensioner-concession-card"},
 {n:"Health Care Card",c:"Concessions",k:"health care card concession medicine payment",s:"A concession card linked to certain Centrelink payments and circumstances.",who:"Generally issued with qualifying payments or supplements.",amount:"Not a cash payment; concessions can include cheaper medicines and other benefits.",need:"Qualifying payment/circumstances.",apply:"Often issued automatically where eligible.",u:"https://www.servicesaustralia.gov.au/health-care-card"},
 {n:"Rent Assistance",c:"Housing & supplements",k:"rent rental housing board lodging help rent assistance",s:"Extra payment to help with rent for eligible people receiving certain payments.",who:"You generally need to receive an eligible payment and pay enough rent, board or lodging.",amount:"Rate depends on rent paid, family situation and applicable thresholds.",need:"Rent/board/lodging amount and qualifying payment details.",apply:"Usually assessed as part of an eligible Centrelink payment.",u:"https://www.servicesaustralia.gov.au/rent-assistance"},
 {n:"Remote Area Allowance",c:"Housing & supplements",k:"remote area allowance rural remote tax zone",s:"Extra help for some income-support recipients living in eligible remote areas.",who:"Requires an eligible income-support payment and residence in the relevant tax zone.",amount:"A supplementary fortnightly amount may apply.",need:"Address and qualifying payment details.",apply:"Usually linked to your main payment.",u:"https://www.servicesaustralia.gov.au/remote-area-allowance"},
 {n:"Pension Supplement",c:"Housing & supplements",k:"pension supplement bills utilities phone medicine",s:"Extra support included with certain pension payments to help with regular costs.",who:"Available with certain qualifying pensions and circumstances.",amount:"Amount depends on pension and circumstances.",need:"Usually tied to existing pension eligibility.",apply:"Generally paid with the qualifying pension.",u:"https://www.servicesaustralia.gov.au/pension-supplement"},
 {n:"Pharmaceutical Allowance",c:"Housing & supplements",k:"pharmaceutical medicine medication allowance prescriptions",s:"Help with medicine costs for some eligible payment recipients.",who:"Eligibility is linked to certain payments and circumstances.",amount:"A supplementary amount may be paid.",need:"Qualifying payment details.",apply:"Generally linked to the main payment.",u:"https://www.servicesaustralia.gov.au/pharmaceutical-allowance"},
 {n:"Telephone Allowance",c:"Housing & supplements",k:"telephone phone internet allowance bills",s:"Help with phone and internet costs for some eligible recipients.",who:"Eligibility depends on qualifying payment/card and service circumstances.",amount:"A quarterly allowance may apply.",need:"Qualifying payment/card and phone/internet details.",apply:"Check Services Australia eligibility.",u:"https://www.servicesaustralia.gov.au/telephone-allowance"},
 {n:"Youth Disability Supplement",c:"Housing & supplements",k:"youth disability supplement young dsp youth allowance",s:"Extra support for some young people with disability receiving an eligible payment.",who:"Linked to qualifying disability and payment circumstances.",amount:"A supplementary amount may be included with the main payment.",need:"Age, disability and qualifying payment details.",apply:"Usually assessed with the main payment.",u:"https://www.servicesaustralia.gov.au/youth-disability-supplement"},
 {n:"Crisis Payment",c:"Special circumstances",k:"crisis emergency domestic violence disaster prison humanitarian extreme circumstances",s:"A one-off payment for eligible people in certain severe or extreme circumstances.",who:"Specific crisis categories, timing and eligibility rules apply.",amount:"One-off assistance is based on the relevant rules.",need:"Evidence and details of the crisis circumstances.",apply:"Contact/claim quickly because time limits can apply.",u:"https://www.servicesaustralia.gov.au/crisis-payment"},
 {n:"Special Benefit",c:"Special circumstances",k:"special benefit hardship no other payment financial hardship",s:"Financial help for some people in severe financial hardship who cannot get another income-support payment.",who:"Strict eligibility, income/assets and hardship rules apply.",amount:"Rate depends on circumstances.",need:"Income, assets, residence/visa and hardship details.",apply:"Claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/special-benefit"},
 {n:"Farm Household Allowance",c:"Work",k:"farm farmer farming rural hardship household allowance",s:"Support for eligible farming families experiencing financial hardship.",who:"Farmers and partners who meet farm, income, assets and other requirements.",amount:"Income support plus related assistance may apply.",need:"Farm, income, assets and business details.",apply:"Claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/farm-household-allowance"},
 {n:"Assistance for Isolated Children Scheme",c:"Study",k:"isolated children remote school boarding distance education",s:"Help for families whose children cannot attend an appropriate government school locally because of location or special circumstances.",who:"Different allowances have different schooling and isolation requirements.",amount:"Various allowances may be available.",need:"Schooling, location and living arrangement details.",apply:"Claim through Services Australia.",u:"https://www.servicesaustralia.gov.au/assistance-for-isolated-children-scheme"}
];

let supportCategory="all";
function norm(v){return (v||"").toLowerCase().replace(/[^a-z0-9 ]/g," ")}
function renderSupport(){
 const q=norm($('supportQuery').value);
 const words=q.split(/\s+/).filter(Boolean);
 let rows=SUPPORT_CATALOGUE.filter(x=>{
   const cat=supportCategory==="all"||x.c===supportCategory;
   const hay=norm(x.n+" "+x.c+" "+x.k+" "+x.s);
   return cat && (!words.length||words.every(w=>hay.includes(w)));
 });
 $('supportCount').textContent=`${rows.length} support option${rows.length===1?'':'s'} found`;
 $('supportResults').innerHTML=rows.length?rows.map((x,i)=>`<article class="support-item" data-support="${SUPPORT_CATALOGUE.indexOf(x)}"><span class="type">${x.c}</span><h3>${x.n}</h3><p>${x.s}</p><span class="read">Read simple guide →</span></article>`).join(''):`<div class="no-support"><h3>No exact match</h3><p>Try simpler words such as “rent”, “baby”, “study”, “carer” or “job”. The eligibility checker can also search based on your circumstances.</p></div>`;
 document.querySelectorAll('[data-support]').forEach(el=>el.onclick=()=>openSupport(+el.dataset.support));
}
function openSupport(i){
 const x=SUPPORT_CATALOGUE[i];
 $('supportDetail').innerHTML=`<article class="support-detail"><span class="eyebrow">${x.c}</span><h2>${x.n}</h2><p class="lead">${x.s}</p><div class="support-detail-grid"><div class="info-box"><h4>Who may qualify?</h4><p>${x.who}</p></div><div class="info-box"><h4>How much?</h4><p>${x.amount}</p></div><div class="info-box"><h4>What might I need?</h4><p>${x.need}</p></div><div class="info-box"><h4>How do I apply?</h4><p>${x.apply}</p></div></div><div class="support-note"><b>Pre-application guide:</b> Finally Entitled helps you understand what may apply before you claim. Government agencies make the final eligibility decision.</div><div class="official-bottom"><a class="primary" href="${x.u}" target="_blank" rel="noopener">Official information / apply →</a></div></article>`;
 $('supportDetail').scrollIntoView({behavior:'smooth',block:'start'});
}
$('supportQuery').addEventListener('input',renderSupport);
document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{$('supportQuery').value=b.dataset.search;supportCategory='all';document.querySelectorAll('.cat').forEach(c=>c.classList.toggle('active',c.dataset.cat==='all'));renderSupport()});
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{supportCategory=b.dataset.cat;document.querySelectorAll('.cat').forEach(c=>c.classList.toggle('active',c===b));renderSupport()});
renderSupport();

refreshIncome();syncRelationship();syncHousing();showStep(1);