const fs=require("fs"),vm=require("vm"); global.window={};
vm.runInThisContext(fs.readFileSync("rules-2026-27.js","utf8"));
const R=window.FE_RULES,C=window.FE_CALCULATORS;
const eq=(a,e,n)=>{if(typeof a==="number"&&typeof e==="number"){if(Math.abs(a-e)>1e-9)throw new Error(`${n}: expected ${e}, got ${a}`)}else if(a!==e)throw new Error(`${n}: expected ${e}, got ${a}`)};
eq(R.ftbB.primaryEarnerAnnualLimit,124327,"FTB B primary limit");
eq(R.ftbB.maxRatePerFamilyFortnight.youngest0to4,200.34,"FTB B under 5 max");
eq(C.ftbBEstimate({single:true,primaryIncome:100000,youngestAge:3}).fortnightly,200.34,"FTB B single");
eq(C.ftbBEstimate({primaryIncome:100000,secondaryIncome:7154,youngestAge:3}).fortnightly,200.34,"FTB B secondary free area");
eq(C.ftbBEstimate({primaryIncome:130000,secondaryIncome:0,youngestAge:3}).eligible,false,"FTB B primary cutoff");
eq(R.parentingPayment.maxFortnightly.single,1037.50,"Parenting Payment single");
eq(C.parentingSingleIncomeFreeArea(1),232.60,"PP 1 child free area");
eq(C.parentingSingleIncomeFreeArea(4),306.40,"PP 4 child free area");
eq(R.jobSeeker.maxFortnightly.singleNoChildren,824.90,"JobSeeker single");
eq(R.jobSeeker.income.cutoffs.singleNoChildren,1557.17,"JobSeeker cutoff");
eq(C.rentAssistanceSingle(157.80),0,"RA threshold");
eq(C.rentAssistanceSingle(456.20),223.80,"RA single maximum");
eq(C.rentAssistanceSingle(356.74,true),149.20,"RA sharer maximum");
eq(C.ccsStandardPercentage(88520),90,"CCS threshold");
console.log("✓ Finally Entitled structured rules batch 2 passed");
