const fs=require("fs"),vm=require("vm"); global.window={FE_RULES:{},FE_CALCULATORS:{}};
vm.runInThisContext(fs.readFileSync("rules-batch-3-2026-27.js","utf8"));
const R=window.FE_RULES,C=window.FE_CALCULATORS;
const eq=(a,e,n)=>{if(typeof a==="number"&&typeof e==="number"){if(Math.abs(a-e)>1e-9)throw Error(`${n}: ${a} != ${e}`)}else if(a!==e)throw Error(`${n}: ${a} != ${e}`)};
eq(R.agePension.maxFortnightly.single.total,1237.70,"Age Pension single");
eq(R.dsp.age21PlusMaxFortnightly.single.total,1237.70,"DSP single 21+");
eq(R.carerPayment.maxFortnightly.coupleCombined.total,1866.00,"Carer Payment couple");
eq(R.carerPayment.income.singleFreeAreaFortnight,226,"Carer free area");
eq(C.carerPaymentSingleIncomeReduction(326),50,"Carer reduction");
eq(R.parentalLeavePay.dailyBeforeTax,200.94,"PLP daily");
eq(R.parentalLeavePay.familyDaysIfBirthOrAdoptionFrom20260701,130,"PLP days");
eq(C.parentalLeavePayGross(130),26122.20,"PLP 130 day gross");
eq(C.parentalLeavePayIncomeTest(186487,500000).passes,true,"PLP individual");
eq(C.parentalLeavePayIncomeTest(200000,386525).passes,true,"PLP family");
eq(C.parentalLeavePayIncomeTest(200000,400000).passes,false,"PLP fail");
eq(R.newborn.upfrontPaymentPerChild,708,"Newborn upfront");
eq(R.newborn.supplementMax13Weeks.firstChild,2125.76,"Newborn supplement first");
eq(R.stillbornBabyPayment.lumpSum,4482.12,"Stillborn payment");
eq(C.pensionAssetBand({single:true,homeowner:true,assets:333000}),"full-rate-assets-band","Pension full assets");
eq(C.pensionAssetBand({single:true,homeowner:true,assets:500000}),"part-pension-assets-band","Pension part assets");
console.log("✓ Finally Entitled Batch 3 tests passed");